export const listData = [
    {
      id: 1,
      title: "Digital Billboard at Cox's Bazar Beach",
      images:[ "https://www.tbsnews.net/sites/default/files/styles/big_3/public/images/2024/11/13/img_2209.jpeg"],
      type: "Billboard",
      pricePerHour: 700,
      location: "Cox's Bazar Beach Road, Bangladesh",
      latitude: 21.4272,
      longitude: 92.0058,
      availableSlots: 3,
      rating: 4.8,
      footTrafficPerDay: 15000,
    },
    {
      id: 2,
      title: "Indoor Ad Space at Star Cineplex",
      images:["https://digitaloohad.com/wp-content/uploads/2024/09/Bcity-Indoor-Converted.jpg"],
      type: "Indoor Digital Screen",
      pricePerHour: 400,
      location: "Bashundhara City, Dhaka, Bangladesh",
      latitude: 23.7509,
      longitude: 90.3911,
      availableSlots: 5,
      rating: 4.5,
      footTrafficPerDay: 8000,
    },
    {
      id: 3,
      title: "Shop Window Ad Space in Dhanmondi",
      images:["https://digitaloohad.com/wp-content/uploads/2024/09/Bcity-Indoor-Converted.jpg"],
      type: "Window Poster",
      pricePerHour: 250,
      location: "Dhanmondi 27, Dhaka, Bangladesh",
      latitude: 23.7465,
      longitude: 90.3743,
      availableSlots: 2,
      rating: 4.3,
      footTrafficPerDay: 5000,
    },
    {
      id: 4,
      title: "Digital Screen in Banani Cafe",
      images:["https://digitaloohad.com/wp-content/uploads/2024/09/Bcity-Indoor-Converted.jpg"],
      type: "Indoor Digital Screen",
      pricePerHour: 350,
      location: "Banani Road 11, Dhaka, Bangladesh",
      latitude: 23.7936,
      longitude: 90.4061,
      availableSlots: 4,
      rating: 4.6,
      footTrafficPerDay: 6500,
    },
    {
      id: 5,
      title: "Street Banner at Shahbagh Intersection",
      images:["https://digitaloohad.com/wp-content/uploads/2024/09/Bcity-Indoor-Converted.jpg"],
      type: "Street Banner",
      pricePerHour: 300,
      location: "Shahbagh, Dhaka, Bangladesh",
      latitude: 23.7361,
      longitude: 90.3967,
      availableSlots: 6,
      rating: 4.2,
      footTrafficPerDay: 9000,
    },
  ];
  
  export const singlePostData = {
    id: 1,
    title: "High-Visibility Digital Billboard in Dhaka",
    pricePerHour: 900,
    images: [
    "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    type: "Billboard",
    size: "15ft x 10ft",
    latitude: 23.8103,
    longitude: 90.4125,
    city: "Dhaka",
    location: "Gulshan Avenue, Dhaka, Bangladesh",
    rating: 4.9,
    footTrafficPerDay: 20000,
    visibility: "Prime road-side location",
    description:
      "Perfect advertising spot in a high-traffic commercial area of Dhaka. Ideal for brand promotions, events, and campaign visibility.",
  };
  
  export const userData = {
    id: 1,
    name: "Mujib",
    img: "https://dailyasianage.com/library/1710618099_2.jpg?v=0,1",
  };
  